version: '3.8'

services:
  frontend:
    build: ./Onlyren_Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Onlyren_Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

  backend:
    build: ./Onlyren_Backend
    volumes:
      - ./Onlyren_Backend:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mysql
    command: php-fpm


  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Onlyren_Backend:/var/www/html
      - ./Onlyren_Backend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: onlyrent_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  