version: '3.8'

services:
  frontend:
    build:
      context: ./Onlyren_Frontend
      target: development  # Use development stage
    ports:
      - "3000:3000"
    volumes:
      - ./Onlyren_Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./Onlyren_Backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./Onlyren_Backend:/var/www/html
      - vendor_cache:/var/www/html/vendor
    expose:
      - "9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Onlyren_Backend:/var/www/html
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: onlyrent_db
    volumes:
      - mysql_dev_data:/var/lib/mysql

volumes:
  mysql_dev_data:
  vendor_cache: